### ISSUE TITLE
unit test with Python 2.7 fails AssertEquals: AttributeError: 'KolabWAPTestHelpers' object has no attribute '_type_equality_funcs'

### ISSUE THREAD

**Issue by tpokorra** [TBits/KolabScripts#48]
Debian comes with Python 2.7, while Centos works fine with Python 2.6.

see also http://trac.sagemath.org/ticket/9958

```
[00934] E
[00934] ======================================================================
[00934] ERROR: test_edit_user_password (__main__.KolabRoundcubeChangePassword)
[00934] ----------------------------------------------------------------------
[00934] Traceback (most recent call last):
[00934]   File "./testRoundcubeChangePassword.py", line 60, in test_edit_user_password
[00934]     kolabWAPhelper.login_roundcube("/roundcubemail", emailLogin, password)
[00934]   File "/root/lbs-kolab-test/kolab-test/KolabScripts-master/pySeleniumTests/helperKolabWAP.py", line 163, in login_roundcube
[00934]     self.assertEquals("", "404 not found", "error fetching page")
[00934]   File "/usr/lib/python2.7/unittest/case.py", line 515, in assertEqual
[00934]     assertion_func = self._getAssertEqualityFunc(first, second)
[00934]   File "/usr/lib/python2.7/unittest/case.py", line 496, in _getAssertEqualityFunc
[00934]     asserter = self._type_equality_funcs.get(type(first))
[00934] AttributeError: 'KolabWAPTestHelpers' object has no attribute '_type_equality_funcs'
```

**Comment by tpokorra** [comment]
still happens on lbs?
see also https://github.com/OniOni/python-parallel-wd/pull/5

**Comment by tpokorra** [comment]
see also https://groups.google.com/forum/#!topic/sage-devel/4AgYA1ShUPM
